from . import hr_kpi_setup
from . import hr_kpi_dashboard
from . import hr_kpi_type
from . import hr_kpi_points_tbl
from . import hr_kpi_points_label
from . import hr_kpi_groups
from . import hr_kpi_cmpd_pt
from . import hr_emp_kpi
from . import hr_emp_kpi_entry
from . import hr_desig_points
from . import hr_emp_kpi_calc
from . import hr_kpi_category
from . import hr_contract
